import { IoHeart, IoNotifications } from "react-icons/io5";
import { IoMdSettings } from "react-icons/io";

export const navLinks = [
  { linkTitle: "Favourites", icon: <IoHeart className="nav-link" />, id: 0 },
  {
    linkTitle: "Notifications",
    icon: <IoNotifications className="nav-link" />,
    id: 1,
  },
  { linkTitle: "Settings", icon: <IoMdSettings className="nav-link" />, id: 2 },
];

export const carsData = {
  sports: [
    {
      name: "Porsche 911 Carrera",
      fuelTankCapacity: "63 L",
      price: 122095,
      seatingCapacity: 4,
      transmission: "Automatic / Manual",
    },
    {
      name: "Chevrolet Corvette",
      fuelTankCapacity: "70 L",
      price: 117990,
      seatingCapacity: 2,
      transmission: "Automatic",
    },
    {
      name: "Ford Mustang GT",
      fuelTankCapacity: "61 L",
      price: 60360,
      seatingCapacity: 4,
      transmission: "Manual / Automatic",
    },
    {
      name: "Nissan GT-R",
      fuelTankCapacity: "74 L",
      price: 120000,
      seatingCapacity: 4,
      transmission: "Automatic",
    },
    {
      name: "Lamborghini Huracán",
      fuelTankCapacity: "83 L",
      price: 230000,
      seatingCapacity: 2,
      transmission: "Automatic",
    },
    {
      name: "Ferrari F8 Tributo",
      fuelTankCapacity: "78 L",
      price: 280000,
      seatingCapacity: 2,
      transmission: "Automatic",
    },
    {
      name: "McLaren 720S",
      fuelTankCapacity: "72 L",
      price: 305000,
      seatingCapacity: 2,
      transmission: "Automatic",
    },
    {
      name: "Aston Martin Vantage",
      fuelTankCapacity: "73 L",
      price: 150000,
      seatingCapacity: 2,
      transmission: "Automatic",
    },
    {
      name: "Jaguar F-Type",
      fuelTankCapacity: "70 L",
      price: 79900,
      seatingCapacity: 2,
      transmission: "Automatic / Manual",
    },
    {
      name: "Toyota GR Supra",
      fuelTankCapacity: "52 L",
      price: 56000,
      seatingCapacity: 2,
      transmission: "Automatic",
    },
    {
      name: "Mazda MX-5 Miata",
      fuelTankCapacity: "45 L",
      price: 30765,
      seatingCapacity: 2,
      transmission: "Manual / Automatic",
    },
    {
      name: "Audi R8",
      fuelTankCapacity: "73 L",
      price: 158600,
      seatingCapacity: 2,
      transmission: "Automatic",
    },
    {
      name: "BMW Z4 Roadster",
      fuelTankCapacity: "52 L",
      price: 53000,
      seatingCapacity: 2,
      transmission: "Automatic / Manual",
    },
    {
      name: "Porsche Cayman 718",
      fuelTankCapacity: "54 L",
      price: 70000,
      seatingCapacity: 2,
      transmission: "Automatic / Manual",
    },
  ],

  suv: [
    {
      name: "Toyota Land Cruiser",
      fuelTankCapacity: "110 L",
      price: 96000,
      seatingCapacity: 7,
      transmission: "Automatic",
    },
    {
      name: "Range Rover Sport",
      fuelTankCapacity: "90 L",
      price: 125000,
      seatingCapacity: 5,
      transmission: "Automatic",
    },
    {
      name: "BMW X5",
      fuelTankCapacity: "80 L",
      price: 72000,
      seatingCapacity: 5,
      transmission: "Automatic",
    },
    {
      name: "Mercedes-Benz G-Class",
      fuelTankCapacity: "100 L",
      price: 139900,
      seatingCapacity: 5,
      transmission: "Automatic",
    },
    {
      name: "Audi Q7",
      fuelTankCapacity: "75 L",
      price: 62000,
      seatingCapacity: 7,
      transmission: "Automatic",
    },
    {
      name: "Kia Telluride",
      fuelTankCapacity: "70 L",
      price: 47000,
      seatingCapacity: 8,
      transmission: "Automatic",
    },
    {
      name: "Hyundai Palisade",
      fuelTankCapacity: "71 L",
      price: 50000,
      seatingCapacity: 8,
      transmission: "Automatic",
    },
    {
      name: "Lexus RX 350",
      fuelTankCapacity: "72 L",
      price: 58000,
      seatingCapacity: 5,
      transmission: "Automatic",
    },
    {
      name: "Honda CR-V",
      fuelTankCapacity: "57 L",
      price: 33000,
      seatingCapacity: 5,
      transmission: "Automatic",
    },
    {
      name: "Toyota Fortuner",
      fuelTankCapacity: "80 L",
      price: 54000,
      seatingCapacity: 7,
      transmission: "Automatic",
    },
    {
      name: "Jeep Grand Cherokee",
      fuelTankCapacity: "93 L",
      price: 61000,
      seatingCapacity: 5,
      transmission: "Automatic",
    },
    {
      name: "Nissan Patrol",
      fuelTankCapacity: "140 L",
      price: 92000,
      seatingCapacity: 7,
      transmission: "Automatic",
    },
    {
      name: "Mazda CX-90",
      fuelTankCapacity: "74 L",
      price: 40000,
      seatingCapacity: 7,
      transmission: "Automatic",
    },
    {
      name: "Volvo XC90",
      fuelTankCapacity: "71 L",
      price: 61000,
      seatingCapacity: 7,
      transmission: "Automatic",
    },
  ],

  mpv: [
    {
      name: "Toyota Innova Crysta",
      fuelTankCapacity: "55 L",
      price: 28000,
      seatingCapacity: 7,
      transmission: "Manual / Automatic",
    },
    {
      name: "Kia Carnival",
      fuelTankCapacity: "60 L",
      price: 47000,
      seatingCapacity: 7,
      transmission: "Automatic",
    },
    {
      name: "Honda Odyssey",
      fuelTankCapacity: "68 L",
      price: 38000,
      seatingCapacity: 8,
      transmission: "Automatic",
    },
    {
      name: "Hyundai Staria",
      fuelTankCapacity: "75 L",
      price: 42000,
      seatingCapacity: 9,
      transmission: "Automatic",
    },
    {
      name: "Toyota Alphard",
      fuelTankCapacity: "75 L",
      price: 90000,
      seatingCapacity: 7,
      transmission: "Automatic",
    },
    {
      name: "Nissan Serena",
      fuelTankCapacity: "55 L",
      price: 32000,
      seatingCapacity: 7,
      transmission: "Automatic",
    },
    {
      name: "Suzuki Ertiga",
      fuelTankCapacity: "45 L",
      price: 18000,
      seatingCapacity: 7,
      transmission: "Manual / Automatic",
    },
    {
      name: "Daihatsu Xenia",
      fuelTankCapacity: "43 L",
      price: 16000,
      seatingCapacity: 7,
      transmission: "Automatic",
    },
    {
      name: "Proton Exora",
      fuelTankCapacity: "55 L",
      price: 23000,
      seatingCapacity: 7,
      transmission: "Automatic",
    },
    {
      name: "Mitsubishi Xpander",
      fuelTankCapacity: "45 L",
      price: 21000,
      seatingCapacity: 7,
      transmission: "Automatic",
    },
    {
      name: "Mazda Biante",
      fuelTankCapacity: "52 L",
      price: 27000,
      seatingCapacity: 8,
      transmission: "Automatic",
    },
    {
      name: "Toyota Avanza",
      fuelTankCapacity: "43 L",
      price: 20000,
      seatingCapacity: 7,
      transmission: "Automatic",
    },
    {
      name: "Peugeot Traveller",
      fuelTankCapacity: "69 L",
      price: 49000,
      seatingCapacity: 8,
      transmission: "Automatic",
    },
    {
      name: "Mercedes-Benz V-Class",
      fuelTankCapacity: "70 L",
      price: 72000,
      seatingCapacity: 8,
      transmission: "Automatic",
    },
  ],

  sedan: [
    {
      name: "Toyota Camry",
      fuelTankCapacity: "60 L",
      price: 27000,
      seatingCapacity: 5,
      transmission: "Automatic",
    },
    {
      name: "Honda Accord",
      fuelTankCapacity: "56 L",
      price: 28000,
      seatingCapacity: 5,
      transmission: "Automatic",
    },
    {
      name: "BMW 3 Series",
      fuelTankCapacity: "59 L",
      price: 45000,
      seatingCapacity: 5,
      transmission: "Automatic",
    },
    {
      name: "Mercedes-Benz C-Class",
      fuelTankCapacity: "66 L",
      price: 47000,
      seatingCapacity: 5,
      transmission: "Automatic",
    },
    {
      name: "Audi A4",
      fuelTankCapacity: "54 L",
      price: 43000,
      seatingCapacity: 5,
      transmission: "Automatic",
    },
    {
      name: "Hyundai Sonata",
      fuelTankCapacity: "60 L",
      price: 25000,
      seatingCapacity: 5,
      transmission: "Automatic",
    },
    {
      name: "Kia K5",
      fuelTankCapacity: "60 L",
      price: 24000,
      seatingCapacity: 5,
      transmission: "Automatic",
    },
    {
      name: "Tesla Model 3",
      fuelTankCapacity: "— (EV)",
      price: 39000,
      seatingCapacity: 5,
      transmission: "Single-speed (EV)",
    },
    {
      name: "Nissan Altima",
      fuelTankCapacity: "60 L",
      price: 27000,
      seatingCapacity: 5,
      transmission: "Automatic",
    },
    {
      name: "Mazda 6",
      fuelTankCapacity: "62 L",
      price: 29000,
      seatingCapacity: 5,
      transmission: "Automatic",
    },
    {
      name: "Volkswagen Passat",
      fuelTankCapacity: "66 L",
      price: 28000,
      seatingCapacity: 5,
      transmission: "Automatic",
    },
    {
      name: "Peugeot 508",
      fuelTankCapacity: "62 L",
      price: 40000,
      seatingCapacity: 5,
      transmission: "Automatic",
    },
    {
      name: "Lexus ES 350",
      fuelTankCapacity: "65 L",
      price: 43000,
      seatingCapacity: 5,
      transmission: "Automatic",
    },
    {
      name: "Honda City",
      fuelTankCapacity: "40 L",
      price: 18000,
      seatingCapacity: 5,
      transmission: "Manual / Automatic",
    },
  ],

  coupe: [
    {
      name: "BMW M4 Coupe",
      fuelTankCapacity: "59 L",
      price: 77000,
      seatingCapacity: 4,
      transmission: "Automatic / Manual",
    },
    {
      name: "Audi TT",
      fuelTankCapacity: "50 L",
      price: 52000,
      seatingCapacity: 4,
      transmission: "Automatic / Manual",
    },
    {
      name: "Mercedes-Benz C-Class Coupe",
      fuelTankCapacity: "66 L",
      price: 55000,
      seatingCapacity: 4,
      transmission: "Automatic",
    },
    {
      name: "Lexus LC 500",
      fuelTankCapacity: "82 L",
      price: 100000,
      seatingCapacity: 4,
      transmission: "Automatic",
    },
    {
      name: "Toyota GR86",
      fuelTankCapacity: "50 L",
      price: 31595,
      seatingCapacity: 4,
      transmission: "Manual / Automatic",
    },
    {
      name: "Subaru BRZ",
      fuelTankCapacity: "50 L",
      price: 34380,
      seatingCapacity: 4,
      transmission: "Manual / Automatic",
    },
    {
      name: "Jaguar F-Type Coupe",
      fuelTankCapacity: "70 L",
      price: 81000,
      seatingCapacity: 2,
      transmission: "Automatic",
    },
    {
      name: "Chevrolet Camaro",
      fuelTankCapacity: "72 L",
      price: 35000,
      seatingCapacity: 4,
      transmission: "Manual / Automatic",
    },
    {
      name: "Ford Mustang Coupe",
      fuelTankCapacity: "61 L",
      price: 32000,
      seatingCapacity: 4,
      transmission: "Manual / Automatic",
    },
    {
      name: "Infiniti Q60",
      fuelTankCapacity: "80 L",
      price: 45000,
      seatingCapacity: 4,
      transmission: "Automatic",
    },
    {
      name: "Dodge Challenger",
      fuelTankCapacity: "70 L",
      price: 30000,
      seatingCapacity: 5,
      transmission: "Manual / Automatic",
    },
    {
      name: "Bentley Continental GT",
      fuelTankCapacity: "90 L",
      price: 240000,
      seatingCapacity: 4,
      transmission: "Automatic",
    },
    {
      name: "Aston Martin Vantage Coupe",
      fuelTankCapacity: "73 L",
      price: 150000,
      seatingCapacity: 2,
      transmission: "Automatic",
    },
    {
      name: "Nissan Z Coupe",
      fuelTankCapacity: "62 L",
      price: 43000,
      seatingCapacity: 2,
      transmission: "Manual / Automatic",
    },
  ],

  hatchback: [
    {
      name: "Volkswagen Golf GTI",
      fuelTankCapacity: "50 L",
      price: 31000,
      seatingCapacity: 5,
      transmission: "Manual / Automatic",
    },
    {
      name: "Honda Civic Hatchback",
      fuelTankCapacity: "47 L",
      price: 25000,
      seatingCapacity: 5,
      transmission: "Automatic",
    },
    {
      name: "Toyota Yaris",
      fuelTankCapacity: "42 L",
      price: 18000,
      seatingCapacity: 5,
      transmission: "Manual / Automatic",
    },
    {
      name: "Hyundai i20",
      fuelTankCapacity: "37 L",
      price: 17000,
      seatingCapacity: 5,
      transmission: "Manual / Automatic",
    },
    {
      name: "Kia Rio",
      fuelTankCapacity: "43 L",
      price: 16500,
      seatingCapacity: 5,
      transmission: "Automatic",
    },
    {
      name: "Ford Fiesta",
      fuelTankCapacity: "42 L",
      price: 19000,
      seatingCapacity: 5,
      transmission: "Manual / Automatic",
    },
    {
      name: "Mazda 3 Hatchback",
      fuelTankCapacity: "51 L",
      price: 25000,
      seatingCapacity: 5,
      transmission: "Automatic",
    },
    {
      name: "Suzuki Swift",
      fuelTankCapacity: "37 L",
      price: 15000,
      seatingCapacity: 5,
      transmission: "Manual / Automatic",
    },
    {
      name: "Mini Cooper",
      fuelTankCapacity: "44 L",
      price: 29000,
      seatingCapacity: 4,
      transmission: "Automatic / Manual",
    },
    {
      name: "Audi A3 Sportback",
      fuelTankCapacity: "50 L",
      price: 36000,
      seatingCapacity: 5,
      transmission: "Automatic",
    },
    {
      name: "Peugeot 208",
      fuelTankCapacity: "44 L",
      price: 21000,
      seatingCapacity: 5,
      transmission: "Automatic",
    },
    {
      name: "Renault Clio",
      fuelTankCapacity: "42 L",
      price: 20000,
      seatingCapacity: 5,
      transmission: "Manual / Automatic",
    },
    {
      name: "BMW 1 Series",
      fuelTankCapacity: "50 L",
      price: 35000,
      seatingCapacity: 5,
      transmission: "Automatic",
    },
    {
      name: "Mercedes-Benz A-Class",
      fuelTankCapacity: "51 L",
      price: 37000,
      seatingCapacity: 5,
      transmission: "Automatic",
    },
  ],
};
export const footerLinks = [
  {
    header: "About",
    sublinks: [
      { title: "How it works", link: "", id: 0 },
      { title: "Featured", link: "https://www.discord.com", id: 1 },
      { title: "Partnership", link: "https://www.discord.com", id: 2 },
      { title: "Bussiness Relation", link: "https://www.discord.com", id: 3 },
    ],
  },
  {
    header: "Community",
    sublinks: [
      { title: "Events", link: "https://www.discord.com", id: 0 },
      { title: "Blog", link: "https://www.discord.com", id: 1 },
      { title: "Podcast", link: "https://www.discord.com", id: 2 },
      { title: "Invite a friend", link: "https://www.discord.com", id: 3 },
    ],
  },
  {
    header: "Socials",
    sublinks: [
      { title: "Discord", link: "https://www.discord.com", id: 0 },
      { title: "Instagram", link: "https://www.instagram.com", id: 1 },
      { title: "Twitter", link: "https://www.twitter.com", id: 2 },
      { title: "Facebook", link: "https://www.facebook.com", id: 3 },
    ],
  },
];
