import { IoHeart, IoNotifications } from "react-icons/io5";
import { IoMdSettings } from "react-icons/io";

export const navLinks = [
  { linkTitle: "Favourites", icon: <IoHeart className="nav-link" />, id: 0 },
  {
    linkTitle: "Notifications",
    icon: <IoNotifications className="nav-link" />,
    id: 1,
  },
  { linkTitle: "Settings", icon: <IoMdSettings className="nav-link" />, id: 2 },
];

export const carsData = {
  sports: [
    {
      id: 1,

      name: "Porsche 911 Carrera",
      fuelTankCapacity: "63 L",
      rent: 90.25,
      actualRent: 95.0,
      changeRentPrice: 4.75,
      seatingCapacity: 4,
      transmission: "Automatic / Manual",
      img: "./images/sports/porsche_911_carrera.png",
      alt: "Image of a Porsche 911 Carrera sports car",
      favourite: true,
      rating: 4.8,
      reviewersCount: 215,
      description:
        "Experience the perfect blend of performance and luxury with this iconic sports car.",
    },
    {
      id: 2,

      name: "Chevrolet Corvette",
      fuelTankCapacity: "70 L",
      rent: 87.49,
      actualRent: 92.0,
      changeRentPrice: 4.51,
      seatingCapacity: 2,
      transmission: "Automatic",
      img: "/images/sports/chevrolet_corvette.png",
      alt: "Image of a Chevrolet Corvette sports car",
      favourite: false,
      rating: 4.4,
      reviewersCount: 350,
      description:
        "Experience the perfect blend of performance and luxury with this iconic sports car.",
    },
    {
      id: 3,

      name: "Ford Mustang GT",
      fuelTankCapacity: "61 L",
      rent: 53.4,
      actualRent: 56.0,
      changeRentPrice: 2.6,
      seatingCapacity: 4,
      transmission: "Manual / Automatic",
      img: "/images/sports/ford_mustang_gt.jpg",
      alt: "Image of a Ford Mustang GT sports car",
      favourite: true,
      rating: 4.0,
      reviewersCount: 480,
      description:
        "Experience the perfect blend of performance and luxury with this iconic sports car.",
    },
    {
      id: 4,

      name: "Nissan GT-R",
      fuelTankCapacity: "74 L",
      rent: 88.66,
      actualRent: 94.0,
      changeRentPrice: 5.34,
      seatingCapacity: 4,
      transmission: "Automatic",
      img: "/images/sports/nissan_gt_r.jpg",
      alt: "Image of a Nissan GT-R sports car",
      favourite: false,
      rating: 4.6,
      reviewersCount: 155,
      description:
        "Experience the perfect blend of performance and luxury with this iconic sports car.",
    },
    {
      id: 5,

      name: "Lamborghini Huracán",
      fuelTankCapacity: "83 L",
      rent: 91.2,
      actualRent: 98.0,
      changeRentPrice: 6.8,
      seatingCapacity: 2,
      transmission: "Automatic",
      img: "/images/sports/huracan.jpg",
      alt: "Image of a Lamborghini Huracán sports car",
      favourite: true,
      rating: 4.9,
      reviewersCount: 98,
      description:
        "Experience the perfect blend of performance and luxury with this iconic sports car.",
    },
    {
      id: 6,

      name: "Ferrari F8 Tributo",
      fuelTankCapacity: "78 L",
      rent: 92.8,
      actualRent: 99.0,
      changeRentPrice: 6.2,
      seatingCapacity: 2,
      transmission: "Automatic",
      img: "/images/sports/f8-tributo.jpg",
      alt: "Image of a Ferrari F8 Tributo sports car",
      favourite: false,
      rating: 4.7,
      reviewersCount: 105,
      description:
        "Experience the perfect blend of performance and luxury with this iconic sports car.",
    },
    {
      id: 7,

      name: "McLaren 720S",
      fuelTankCapacity: "72 L",
      rent: 93.5,
      actualRent: 99.5,
      changeRentPrice: 6.0,
      seatingCapacity: 2,
      transmission: "Automatic",
      img: "/images/sports/720s.jpg",
      alt: "Image of a McLaren 720S sports car",
      favourite: false,
      rating: 4.8,
      reviewersCount: 88,
      description:
        "Experience the perfect blend of performance and luxury with this iconic sports car.",
    },
    {
      id: 8,

      name: "Aston Martin Vantage",
      fuelTankCapacity: "73 L",
      rent: 85.0,
      actualRent: 90.0,
      changeRentPrice: 5.0,
      seatingCapacity: 2,
      transmission: "Automatic",
      img: "/images/sports/vantage.jpg",
      alt: "Image of an Aston Martin Vantage sports car",
      favourite: true,
      rating: 4.3,
      reviewersCount: 190,
      description:
        "Experience the perfect blend of performance and luxury with this iconic sports car.",
    },
    {
      id: 9,

      name: "Jaguar F-Type",
      fuelTankCapacity: "70 L",
      rent: 78.9,
      actualRent: 85.0,
      changeRentPrice: 6.1,
      seatingCapacity: 2,
      transmission: "Automatic / Manual",
      img: "/images/sports/f-type.jpg",
      alt: "Image of a Jaguar F-Type sports car",
      favourite: false,
      rating: 4.2,
      reviewersCount: 270,
      description:
        "Experience the perfect blend of performance and luxury with this iconic sports car.",
    },
    {
      id: 10,

      name: "Toyota GR Supra",
      fuelTankCapacity: "52 L",
      rent: 51.9,
      actualRent: 56.0,
      changeRentPrice: 4.1,
      seatingCapacity: 2,
      transmission: "Automatic",
      img: "/images/sports/gr-supra.jpg",
      alt: "Image of a Toyota GR Supra sports car",
      favourite: true,
      rating: 3.9,
      reviewersCount: 410,
      description:
        "Experience the perfect blend of performance and luxury with this iconic sports car.",
    },
    {
      id: 11,

      name: "Mazda MX-5 Miata",
      fuelTankCapacity: "45 L",
      rent: 30.77,
      actualRent: 33.0,
      changeRentPrice: 2.23,
      seatingCapacity: 2,
      transmission: "Manual / Automatic",
      img: "/images/sports/mx5-miata.jpg",
      alt: "Image of a Mazda MX-5 Miata sports car",
      favourite: false,
      rating: 4.1,
      reviewersCount: 450,
      description:
        "Experience the perfect blend of performance and luxury with this iconic sports car.",
    },
    {
      id: 12,

      name: "Audi R8",
      fuelTankCapacity: "73 L",
      rent: 89.5,
      actualRent: 96.0,
      changeRentPrice: 6.5,
      seatingCapacity: 2,
      transmission: "Automatic",
      img: "/images/sports/r8.jpg",
      alt: "Image of an Audi R8 sports car",
      favourite: true,
      rating: 4.5,
      reviewersCount: 165,
      description:
        "Experience the perfect blend of performance and luxury with this iconic sports car.",
    },
    {
      id: 13,

      name: "BMW Z4 Roadster",
      fuelTankCapacity: "52 L",
      rent: 51.0,
      actualRent: 55.0,
      changeRentPrice: 4.0,
      seatingCapacity: 2,
      transmission: "Automatic / Manual",
      img: "/images/sports/z4-roadster.jpg",
      alt: "Image of a BMW Z4 Roadster sports car",
      favourite: false,
      rating: 3.8,
      reviewersCount: 320,
      description:
        "Experience the perfect blend of performance and luxury with this iconic sports car.",
    },
    {
      id: 14,

      name: "Porsche Cayman 718",
      fuelTankCapacity: "54 L",
      rent: 70.0,
      actualRent: 76.0,
      changeRentPrice: 6.0,
      seatingCapacity: 2,
      transmission: "Automatic / Manual",
      img: "/images/sports/cayman-718.jpg",
      alt: "Image of a Porsche Cayman 718 sports car",
      favourite: true,
      rating: 4.6,
      reviewersCount: 235,
      description:
        "Experience the perfect blend of performance and luxury with this iconic sports car.",
    },
  ],
  suv: [
    {
      id: 15,
      id: 15,
      name: "Toyota Land Cruiser",
      fuelTankCapacity: "110 L",
      rent: 66,
      actualRent: 71,
      changeRentPrice: 5,
      seatingCapacity: 7,
      transmission: "Automatic",
      img: "/images/suv/land-cruiser-300.jpg",
      alt: "Image of a Toyota Land Cruiser SUV",
      favourite: true,
      rating: 4.7,
      reviewersCount: 180,
      description:
        "Perfect for families and adventurers, offering space, comfort, and rugged capability.",
    },
    {
      id: 16,
      id: 16,
      name: "Range Rover Sport",
      fuelTankCapacity: "90 L",
      rent: 85,
      actualRent: 90,
      changeRentPrice: 5,
      seatingCapacity: 5,
      transmission: "Automatic",
      img: "/images/suv/range-rover-sport.jpg",
      alt: "Image of a Range Rover Sport SUV",
      favourite: false,
      rating: 4.5,
      reviewersCount: 140,
      description:
        "Perfect for families and adventurers, offering space, comfort, and rugged capability.",
    },
    {
      id: 17,
      id: 17,
      name: "BMW X5",
      fuelTankCapacity: "80 L",
      rent: 60,
      actualRent: 64,
      changeRentPrice: 4,
      seatingCapacity: 5,
      transmission: "Automatic",
      img: "/images/suv/x5.jpg",
      alt: "Image of a BMW X5 SUV",
      favourite: true,
      rating: 4.2,
      reviewersCount: 220,
      description:
        "Perfect for families and adventurers, offering space, comfort, and rugged capability.",
    },
    {
      id: 18,
      id: 18,
      name: "Mercedes-Benz G-Class",
      fuelTankCapacity: "100 L",
      rent: 93.5,
      actualRent: 99,
      changeRentPrice: 5.5,
      seatingCapacity: 5,
      transmission: "Automatic",
      img: "/images/suv/g-class.jpg",
      alt: "Image of a Mercedes-Benz G-Class SUV",
      favourite: false,
      rating: 4.8,
      reviewersCount: 75,
      description:
        "Perfect for families and adventurers, offering space, comfort, and rugged capability.",
    },
    {
      id: 19,
      id: 19,
      name: "Audi Q7",
      fuelTankCapacity: "75 L",
      rent: 53,
      actualRent: 57,
      changeRentPrice: 4,
      seatingCapacity: 7,
      transmission: "Automatic",
      img: "/images/suv/q7.jpg",
      alt: "Image of an Audi Q7 SUV",
      favourite: true,
      rating: 4.0,
      reviewersCount: 310,
      description:
        "Perfect for families and adventurers, offering space, comfort, and rugged capability.",
    },
    {
      id: 20,
      name: "Kia Telluride",
      fuelTankCapacity: "70 L",
      rent: 40,
      actualRent: 43,
      changeRentPrice: 3,
      seatingCapacity: 8,
      transmission: "Automatic",
      img: "/images/suv/telluride.jpg",
      alt: "Image of a Kia Telluride SUV",
      favourite: false,
      rating: 4.1,
      reviewersCount: 450,
      description:
        "Perfect for families and adventurers, offering space, comfort, and rugged capability.",
    },
    {
      id: 21,
      name: "Hyundai Palisade",
      fuelTankCapacity: "71 L",
      rent: 42.5,
      actualRent: 46,
      changeRentPrice: 3.5,
      seatingCapacity: 8,
      transmission: "Automatic",
      img: "/images/suv/palisade.jpg",
      alt: "Image of a Hyundai Palisade SUV",
      favourite: true,
      rating: 4.3,
      reviewersCount: 390,
      description:
        "Perfect for families and adventurers, offering space, comfort, and rugged capability.",
    },
    {
      id: 22,
      name: "Lexus RX 350",
      fuelTankCapacity: "72 L",
      rent: 49.5,
      actualRent: 53,
      changeRentPrice: 3.5,
      seatingCapacity: 5,
      transmission: "Automatic",
      img: "/images/suv/rx350.jpg",
      alt: "Image of a Lexus RX 350 SUV",
      favourite: false,
      rating: 3.9,
      reviewersCount: 280,
      description:
        "Perfect for families and adventurers, offering space, comfort, and rugged capability.",
    },
    {
      id: 23,
      name: "Honda CR-V",
      fuelTankCapacity: "57 L",
      rent: 28.5,
      actualRent: 31,
      changeRentPrice: 2.5,
      seatingCapacity: 5,
      transmission: "Automatic",
      img: "/images/suv/crv.jpg",
      alt: "Image of a Honda CR-V SUV",
      favourite: false,
      rating: 3.5,
      reviewersCount: 420,
      description:
        "Perfect for families and adventurers, offering space, comfort, and rugged capability.",
    },
    {
      id: 24,
      name: "Toyota Fortuner",
      fuelTankCapacity: "80 L",
      rent: 46,
      actualRent: 49.5,
      changeRentPrice: 3.5,
      seatingCapacity: 7,
      transmission: "Automatic",
      img: "/images/suv/fortuner.jpg",
      alt: "Image of a Toyota Fortuner SUV",
      favourite: true,
      rating: 3.7,
      reviewersCount: 350,
      description:
        "Perfect for families and adventurers, offering space, comfort, and rugged capability.",
    },
    {
      id: 25,
      name: "Jeep Grand Cherokee",
      fuelTankCapacity: "93 L",
      rent: 52,
      actualRent: 56.5,
      changeRentPrice: 4.5,
      seatingCapacity: 5,
      transmission: "Automatic",
      img: "/images/suv/grand-cherokee.jpg",
      alt: "Image of a Jeep Grand Cherokee SUV",
      favourite: false,
      rating: 3.2,
      reviewersCount: 190,
      description:
        "Perfect for families and adventurers, offering space, comfort, and rugged capability.",
    },
    {
      id: 26,
      name: "Nissan Patrol",
      fuelTankCapacity: "140 L",
      rent: 63,
      actualRent: 68.5,
      changeRentPrice: 5.5,
      seatingCapacity: 7,
      transmission: "Automatic",
      img: "/images/suv/patrol.jpg",
      alt: "Image of a Nissan Patrol SUV",
      favourite: true,
      rating: 4.6,
      reviewersCount: 120,
      description:
        "Perfect for families and adventurers, offering space, comfort, and rugged capability.",
    },
    {
      id: 27,
      name: "Mazda CX-90",
      fuelTankCapacity: "74 L",
      rent: 34,
      actualRent: 37,
      changeRentPrice: 3,
      seatingCapacity: 7,
      transmission: "Automatic",
      img: "/images/suv/cx90.jpg",
      alt: "Image of a Mazda CX-90 SUV",
      favourite: false,
      rating: 3.8,
      reviewersCount: 260,
      description:
        "Perfect for families and adventurers, offering space, comfort, and rugged capability.",
    },
    {
      id: 28,
      name: "Volvo XC90",
      fuelTankCapacity: "71 L",
      rent: 52.5,
      actualRent: 56,
      changeRentPrice: 3.5,
      seatingCapacity: 7,
      transmission: "Automatic",
      img: "/images/suv/xc90.jpg",
      alt: "Image of a Volvo XC90 SUV",
      favourite: true,
      rating: 4.4,
      reviewersCount: 290,
      description:
        "Perfect for families and adventurers, offering space, comfort, and rugged capability.",
    },
  ],
  mpv: [
    {
      id: 29,
      id: 29,
      name: "Toyota Innova Crysta",
      fuelTankCapacity: "55 L",
      rent: 24,
      actualRent: 27,
      changeRentPrice: 3,
      seatingCapacity: 7,
      transmission: "Manual / Automatic",
      img: "/images/mpv/innova-crysta-2024.jpg",
      alt: "Image of a Toyota Innova Crysta MPV",
      favourite: true,
      rating: 3.5,
      reviewersCount: 300,
      description:
        "Spacious and versatile, this multi-purpose vehicle is ideal for group travel and long trips.",
    },
    {
      id: 30,

      name: "Kia Carnival",
      fuelTankCapacity: "60 L",
      rent: 38,
      actualRent: 42,
      changeRentPrice: 4,
      seatingCapacity: 7,
      transmission: "Automatic",
      img: "/images/mpv/carnival.jpg",
      alt: "Image of a Kia Carnival MPV",
      favourite: false,
      rating: 3.7,
      reviewersCount: 280,
      description:
        "Spacious and versatile, this multi-purpose vehicle is ideal for group travel and long trips.",
    },
    {
      id: 31,
      name: "Honda Odyssey",
      fuelTankCapacity: "68 L",
      rent: 32,
      actualRent: 36,
      changeRentPrice: 4,
      seatingCapacity: 8,
      transmission: "Automatic",
      img: "/images/mpv/odyssey.jpg",
      alt: "Image of a Honda Odyssey MPV",
      favourite: false,
      rating: 4.0,
      reviewersCount: 350,
      description:
        "Spacious and versatile, this multi-purpose vehicle is ideal for group travel and long trips.",
    },
    {
      id: 32,
      name: "Hyundai Staria",
      fuelTankCapacity: "75 L",
      rent: 35,
      actualRent: 39,
      changeRentPrice: 4,
      seatingCapacity: 9,
      transmission: "Automatic",
      img: "/images/mpv/staria.jpg",
      alt: "Image of a Hyundai Staria MPV",
      favourite: true,
      rating: 4.2,
      reviewersCount: 150,
      description:
        "Spacious and versatile, this multi-purpose vehicle is ideal for group travel and long trips.",
    },
    {
      id: 33,
      name: "Toyota Alphard",
      fuelTankCapacity: "75 L",
      rent: 65,
      actualRent: 70,
      changeRentPrice: 5,
      seatingCapacity: 7,
      transmission: "Automatic",
      img: "/images/mpv/alphard.jpg",
      alt: "Image of a Toyota Alphard MPV",
      favourite: false,
      rating: 4.5,
      reviewersCount: 110,
      description:
        "Spacious and versatile, this multi-purpose vehicle is ideal for group travel and long trips.",
    },
    {
      id: 34,
      name: "Nissan Serena",
      fuelTankCapacity: "55 L",
      rent: 27.5,
      actualRent: 30,
      changeRentPrice: 2.5,
      seatingCapacity: 7,
      transmission: "Automatic",
      img: "/images/mpv/serena.jpg",
      alt: "Image of a Nissan Serena MPV",
      favourite: false,
      rating: 3.4,
      reviewersCount: 250,
      description:
        "Spacious and versatile, this multi-purpose vehicle is ideal for group travel and long trips.",
    },
    {
      id: 35,
      name: "Suzuki Ertiga",
      fuelTankCapacity: "45 L",
      rent: 15,
      actualRent: 17,
      changeRentPrice: 2,
      seatingCapacity: 7,
      transmission: "Manual / Automatic",
      img: "/images/mpv/ertiga.jpg",
      alt: "Image of a Suzuki Ertiga MPV",
      favourite: true,
      rating: 3.1,
      reviewersCount: 400,
      description:
        "Spacious and versatile, this multi-purpose vehicle is ideal for group travel and long trips.",
    },
    {
      id: 36,
      name: "Daihatsu Xenia",
      fuelTankCapacity: "43 L",
      rent: 13.5,
      actualRent: 15.5,
      changeRentPrice: 2,
      seatingCapacity: 7,
      transmission: "Automatic",
      img: "/images/mpv/xenia.jpg",
      alt: "Image of a Daihatsu Xenia MPV",
      favourite: false,
      rating: 3.3,
      reviewersCount: 480,
      description:
        "Spacious and versatile, this multi-purpose vehicle is ideal for group travel and long trips.",
    },
    {
      id: 37,
      name: "Proton Exora",
      fuelTankCapacity: "55 L",
      rent: 19.5,
      actualRent: 22,
      changeRentPrice: 2.5,
      seatingCapacity: 7,
      transmission: "Automatic",
      img: "/images/mpv/exora.jpg",
      alt: "Image of a Proton Exora MPV",
      favourite: true,
      rating: 3.6,
      reviewersCount: 330,
      description:
        "Spacious and versatile, this multi-purpose vehicle is ideal for group travel and long trips.",
    },
    {
      id: 38,
      name: "Mitsubishi Xpander",
      fuelTankCapacity: "45 L",
      rent: 18,
      actualRent: 20.5,
      changeRentPrice: 2.5,
      seatingCapacity: 7,
      transmission: "Automatic",
      img: "/images/mpv/xpander.jpg",
      alt: "Image of a Mitsubishi Xpander MPV",
      favourite: false,
      rating: 3.8,
      reviewersCount: 370,
      description:
        "Spacious and versatile, this multi-purpose vehicle is ideal for group travel and long trips.",
    },
    {
      id: 39,
      name: "Mazda Biante",
      fuelTankCapacity: "52 L",
      rent: 23,
      actualRent: 26,
      changeRentPrice: 3,
      seatingCapacity: 8,
      transmission: "Automatic",
      img: "/images/mpv/biante.jpg",
      alt: "Image of a Mazda Biante MPV",
      favourite: false,
      rating: 3.9,
      reviewersCount: 200,
      description:
        "Spacious and versatile, this multi-purpose vehicle is ideal for group travel and long trips.",
    },
    {
      id: 40,
      name: "Toyota Avanza",
      fuelTankCapacity: "43 L",
      rent: 17,
      actualRent: 20,
      changeRentPrice: 3,
      seatingCapacity: 7,
      transmission: "Automatic",
      img: "/images/mpv/avanza.jpg",
      alt: "Image of a Toyota Avanza MPV",
      favourite: true,
      rating: 3.6,
      reviewersCount: 430,
      description:
        "Spacious and versatile, this multi-purpose vehicle is ideal for group travel and long trips.",
    },
    {
      id: 41,
      name: "Peugeot Traveller",
      fuelTankCapacity: "69 L",
      rent: 40.5,
      actualRent: 44,
      changeRentPrice: 3.5,
      seatingCapacity: 8,
      transmission: "Automatic",
      img: "/images/mpv/traveller.jpg",
      alt: "Image of a Peugeot Traveller MPV",
      favourite: false,
      rating: 4.1,
      reviewersCount: 170,
      description:
        "Spacious and versatile, this multi-purpose vehicle is ideal for group travel and long trips.",
    },
    {
      id: 42,
      name: "Mercedes-Benz V-Class",
      fuelTankCapacity: "70 L",
      rent: 60,
      actualRent: 65,
      changeRentPrice: 5,
      seatingCapacity: 8,
      transmission: "Automatic",
      img: "/images/mpv/v-class.jpg",
      alt: "Image of a Mercedes-Benz V-Class MPV",
      favourite: true,
      rating: 4.6,
      reviewersCount: 95,
      description:
        "Spacious and versatile, this multi-purpose vehicle is ideal for group travel and long trips.",
    },
  ],
  sedan: [
    {
      id: 43,

      name: "Toyota Camry",
      fuelTankCapacity: "60 L",
      rent: 22,
      actualRent: 25,
      changeRentPrice: 3,
      seatingCapacity: 5,
      transmission: "Automatic",
      img: "/images/sedan/camry-2023.jpg",
      alt: "Image of a Toyota Camry sedan",
      favourite: true,
      rating: 3.9,
      reviewersCount: 300,
      description:
        "A comfortable and stylish choice for daily commutes and city cruising.",
    },
    {
      id: 44,

      name: "Honda Accord",
      fuelTankCapacity: "56 L",
      rent: 23,
      actualRent: 26,
      changeRentPrice: 3,
      seatingCapacity: 5,
      transmission: "Automatic",
      img: "/images/sedan/accord-2023.jpg",
      alt: "Image of a Honda Accord sedan",
      favourite: false,
      rating: 4.1,
      reviewersCount: 280,
      description:
        "A comfortable and stylish choice for daily commutes and city cruising.",
    },
    {
      id: 45,
      name: "BMW 3 Series",
      fuelTankCapacity: "59 L",
      rent: 38,
      actualRent: 42,
      changeRentPrice: 4,
      seatingCapacity: 5,
      transmission: "Automatic",
      img: "/images/sedan/3-series.jpg",
      alt: "Image of a BMW 3 Series sedan",
      favourite: true,
      rating: 4.4,
      reviewersCount: 210,
      description:
        "A comfortable and stylish choice for daily commutes and city cruising.",
    },
    {
      id: 46,
      name: "Mercedes-Benz C-Class",
      fuelTankCapacity: "66 L",
      rent: 40,
      actualRent: 44,
      changeRentPrice: 4,
      seatingCapacity: 5,
      transmission: "Automatic",
      img: "/images/sedan/c-class.jpg",
      alt: "Image of a Mercedes-Benz C-Class sedan",
      favourite: false,
      rating: 4.5,
      reviewersCount: 190,
      description:
        "A comfortable and stylish choice for daily commutes and city cruising.",
    },
    {
      id: 47,
      name: "Audi A4",
      fuelTankCapacity: "54 L",
      rent: 36.5,
      actualRent: 40,
      changeRentPrice: 3.5,
      seatingCapacity: 5,
      transmission: "Automatic",
      img: "/images/sedan/a4.jpg",
      alt: "Image of an Audi A4 sedan",
      favourite: true,
      rating: 4.2,
      reviewersCount: 250,
      description:
        "A comfortable and stylish choice for daily commutes and city cruising.",
    },
    {
      id: 48,
      name: "Hyundai Sonata",
      fuelTankCapacity: "60 L",
      rent: 20,
      actualRent: 22,
      changeRentPrice: 2,
      seatingCapacity: 5,
      transmission: "Automatic",
      img: "/images/sedan/sonata.jpg",
      alt: "Image of a Hyundai Sonata sedan",
      favourite: false,
      rating: 3.7,
      reviewersCount: 350,
      description:
        "A comfortable and stylish choice for daily commutes and city cruising.",
    },
    {
      id: 49,
      name: "Kia K5",
      fuelTankCapacity: "60 L",
      rent: 19,
      actualRent: 21,
      changeRentPrice: 2,
      seatingCapacity: 5,
      transmission: "Automatic",
      img: "/images/sedan/k5.jpg",
      alt: "Image of a Kia K5 sedan",
      favourite: false,
      rating: 3.5,
      reviewersCount: 380,
      description:
        "A comfortable and stylish choice for daily commutes and city cruising.",
    },
    {
      id: 50,
      name: "Tesla Model 3",
      fuelTankCapacity: "— (EV)",
      rent: 33,
      actualRent: 36,
      changeRentPrice: 3,
      seatingCapacity: 5,
      transmission: "Single-speed (EV)",
      img: "/images/sedan/model3.jpg",
      alt: "Image of a Tesla Model 3 sedan (EV)",
      favourite: true,
      rating: 4.8,
      reviewersCount: 150,
      description:
        "A comfortable and stylish choice for daily commutes and city cruising.",
    },
    {
      id: 51,
      name: "Nissan Altima",
      fuelTankCapacity: "60 L",
      rent: 22,
      actualRent: 25,
      changeRentPrice: 3,
      seatingCapacity: 5,
      transmission: "Automatic",
      img: "/images/sedan/altima.jpg",
      alt: "Image of a Nissan Altima sedan",
      favourite: false,
      rating: 3.8,
      reviewersCount: 310,
      description:
        "A comfortable and stylish choice for daily commutes and city cruising.",
    },
    {
      id: 52,
      name: "Mazda 6",
      fuelTankCapacity: "62 L",
      rent: 24,
      actualRent: 27,
      changeRentPrice: 3,
      seatingCapacity: 5,
      transmission: "Automatic",
      img: "/images/sedan/mazda6.jpg",
      alt: "Image of a Mazda 6 sedan",
      favourite: true,
      rating: 4.0,
      reviewersCount: 270,
      description:
        "A comfortable and stylish choice for daily commutes and city cruising.",
    },
    {
      id: 53,
      name: "Volkswagen Passat",
      fuelTankCapacity: "66 L",
      rent: 23,
      actualRent: 26,
      changeRentPrice: 3,
      seatingCapacity: 5,
      transmission: "Automatic",
      img: "/images/sedan/passat.jpg",
      alt: "Image of a Volkswagen Passat sedan",
      favourite: false,
      rating: 3.6,
      reviewersCount: 340,
      description:
        "A comfortable and stylish choice for daily commutes and city cruising.",
    },
    {
      id: 54,
      name: "Peugeot 508",
      fuelTankCapacity: "62 L",
      rent: 34,
      actualRent: 37,
      changeRentPrice: 3,
      seatingCapacity: 5,
      transmission: "Automatic",
      img: "/images/sedan/508.jpg",
      alt: "Image of a Peugeot 508 sedan",
      favourite: true,
      rating: 4.1,
      reviewersCount: 220,
      description:
        "A comfortable and stylish choice for daily commutes and city cruising.",
    },
    {
      id: 55,
      name: "Lexus ES 350",
      fuelTankCapacity: "65 L",
      rent: 36.5,
      actualRent: 40,
      changeRentPrice: 3.5,
      seatingCapacity: 5,
      transmission: "Automatic",
      img: "/images/sedan/es350.jpg",
      alt: "Image of a Lexus ES 350 sedan",
      favourite: false,
      rating: 4.3,
      reviewersCount: 180,
      description:
        "A comfortable and stylish choice for daily commutes and city cruising.",
    },
    {
      id: 56,
      name: "Honda City",
      fuelTankCapacity: "40 L",
      rent: 15,
      actualRent: 17,
      changeRentPrice: 2,
      seatingCapacity: 5,
      transmission: "Manual / Automatic",
      img: "/images/sedan/city.jpg",
      alt: "Image of a Honda City sedan",
      favourite: true,
      rating: 3.2,
      reviewersCount: 450,
      description:
        "A comfortable and stylish choice for daily commutes and city cruising.",
    },
  ],
  coupe: [
    {
      id: 57,
      name: "BMW 4 Series Coupe",
      fuelTankCapacity: "59 L",
      rent: 45,
      actualRent: 49,
      changeRentPrice: 4,
      seatingCapacity: 4,
      transmission: "Automatic",
      img: "/images/coupe/4-series.jpg",
      alt: "Image of a BMW 4 Series Coupe",
      favourite: true,
      rating: 4.4,
      reviewersCount: 170,
      description:
        "A sporty two-door design combining performance, luxury, and everyday usability.",
    },
    {
      id: 58,
      name: "Mercedes-Benz E-Class Coupe",
      fuelTankCapacity: "66 L",
      rent: 52,
      actualRent: 56,
      changeRentPrice: 4,
      seatingCapacity: 4,
      transmission: "Automatic",
      img: "/images/coupe/e-class.jpg",
      alt: "Image of a Mercedes-Benz E-Class Coupe",
      favourite: false,
      rating: 4.6,
      reviewersCount: 140,
      description:
        "A sporty two-door design combining performance, luxury, and everyday usability.",
    },
    {
      id: 59,
      name: "Audi A5 Coupe",
      fuelTankCapacity: "58 L",
      rent: 47.5,
      actualRent: 51,
      changeRentPrice: 3.5,
      seatingCapacity: 4,
      transmission: "Automatic",
      img: "/images/coupe/a5.jpg",
      alt: "Image of an Audi A5 Coupe",
      favourite: true,
      rating: 4.3,
      reviewersCount: 190,
      description:
        "A sporty two-door design combining performance, luxury, and everyday usability.",
    },
    {
      id: 60,
      name: "Ford Mustang Coupe",
      fuelTankCapacity: "61 L",
      rent: 55,
      actualRent: 60,
      changeRentPrice: 5,
      seatingCapacity: 4,
      transmission: "Manual / Automatic",
      img: "/images/coupe/mustang.jpg",
      alt: "Image of a Ford Mustang Coupe",
      favourite: true,
      rating: 4.7,
      reviewersCount: 260,
      description:
        "A sporty two-door design combining performance, luxury, and everyday usability.",
    },
    {
      id: 61,
      name: "Chevrolet Camaro",
      fuelTankCapacity: "72 L",
      rent: 53,
      actualRent: 58,
      changeRentPrice: 5,
      seatingCapacity: 4,
      transmission: "Manual / Automatic",
      img: "/images/coupe/camaro.jpg",
      alt: "Image of a Chevrolet Camaro Coupe",
      favourite: false,
      rating: 4.5,
      reviewersCount: 230,
      description:
        "A sporty two-door design combining performance, luxury, and everyday usability.",
    },
    {
      id: 62,
      name: "Toyota GR86",
      fuelTankCapacity: "50 L",
      rent: 39,
      actualRent: 42,
      changeRentPrice: 3,
      seatingCapacity: 4,
      transmission: "Manual / Automatic",
      img: "/images/coupe/gr86.jpg",
      alt: "Image of a Toyota GR86 Coupe",
      favourite: true,
      rating: 4.2,
      reviewersCount: 210,
      description:
        "A sporty two-door design combining performance, luxury, and everyday usability.",
    },
    {
      id: 63,
      name: "Subaru BRZ",
      fuelTankCapacity: "50 L",
      rent: 38.5,
      actualRent: 41,
      changeRentPrice: 2.5,
      seatingCapacity: 4,
      transmission: "Manual / Automatic",
      img: "/images/coupe/brz.jpg",
      alt: "Image of a Subaru BRZ Coupe",
      favourite: false,
      rating: 4.1,
      reviewersCount: 185,
      description:
        "A sporty two-door design combining performance, luxury, and everyday usability.",
    },
    {
      id: 64,
      name: "Porsche 911 Turbo",
      fuelTankCapacity: "67 L",
      rent: 95,
      actualRent: 102,
      changeRentPrice: 7,
      seatingCapacity: 4,
      transmission: "Automatic",
      img: "/images/coupe/Porsche 911 Turbo.png",
      alt: "Image of a Porsche 911 Turbo Coupe",
      favourite: true,
      rating: 4.9,
      reviewersCount: 95,
      description:
        "A sporty two-door design combining performance, luxury, and everyday usability.",
    },
    {
      id: 65,
      name: "Lexus RC",
      fuelTankCapacity: "66 L",
      rent: 42,
      actualRent: 46,
      changeRentPrice: 4,
      seatingCapacity: 4,
      transmission: "Automatic",
      img: "/images/coupe/Lexus RC.png",
      alt: "Image of a Lexus RC Coupe",
      favourite: false,
      rating: 4.0,
      reviewersCount: 160,
      description:
        "A sporty two-door design combining performance, luxury, and everyday usability.",
    },
    {
      id: 66,
      name: "Nissan Z",
      fuelTankCapacity: "62 L",
      rent: 48,
      actualRent: 52,
      changeRentPrice: 4,
      seatingCapacity: 2,
      transmission: "Manual / Automatic",
      img: "/images/coupe/nissan-z.jpg",
      alt: "Image of a Nissan Z Coupe",
      favourite: true,
      rating: 4.6,
      reviewersCount: 140,
      description:
        "A sporty two-door design combining performance, luxury, and everyday usability.",
    },
  ],
  hatchback: [
    {
      id: 67,
      name: "Volkswagen Golf",
      fuelTankCapacity: "50 L",
      rent: 18,
      actualRent: 20,
      changeRentPrice: 2,
      seatingCapacity: 5,
      transmission: "Manual / Automatic",
      img: "/images/hatchback/golf.jpg",
      alt: "Image of a Volkswagen Golf hatchback",
      favourite: true,
      rating: 4.0,
      reviewersCount: 420,
      description:
        "A compact and efficient hatchback perfect for city driving and daily use.",
    },
    {
      id: 68,
      name: "Ford Focus",
      fuelTankCapacity: "52 L",
      rent: 17,
      actualRent: 19,
      changeRentPrice: 2,
      seatingCapacity: 5,
      transmission: "Manual / Automatic",
      img: "/images/hatchback/focus.jpg",
      alt: "Image of a Ford Focus hatchback",
      favourite: false,
      rating: 3.8,
      reviewersCount: 390,
      description:
        "A compact and efficient hatchback perfect for city driving and daily use.",
    },
    {
      id: 69,
      name: "Toyota Corolla Hatchback",
      fuelTankCapacity: "50 L",
      rent: 16,
      actualRent: 18,
      changeRentPrice: 2,
      seatingCapacity: 5,
      transmission: "Automatic",
      img: "/images/hatchback/corolla.jpg",
      alt: "Image of a Toyota Corolla hatchback",
      favourite: true,
      rating: 3.9,
      reviewersCount: 450,
      description:
        "A compact and efficient hatchback perfect for city driving and daily use.",
    },
    {
      id: 70,
      name: "Honda Civic Hatchback",
      fuelTankCapacity: "47 L",
      rent: 19,
      actualRent: 21,
      changeRentPrice: 2,
      seatingCapacity: 5,
      transmission: "Manual / Automatic",
      img: "/images/hatchback/civic.jpg",
      alt: "Image of a Honda Civic hatchback",
      favourite: true,
      rating: 4.1,
      reviewersCount: 430,
      description:
        "A compact and efficient hatchback perfect for city driving and daily use.",
    },
    {
      id: 71,
      name: "Hyundai i30",
      fuelTankCapacity: "50 L",
      rent: 15,
      actualRent: 17,
      changeRentPrice: 2,
      seatingCapacity: 5,
      transmission: "Automatic",
      img: "/images/hatchback/i30.jpg",
      alt: "Image of a Hyundai i30 hatchback",
      favourite: false,
      rating: 3.6,
      reviewersCount: 360,
      description:
        "A compact and efficient hatchback perfect for city driving and daily use.",
    },
    {
      id: 72,
      name: "Kia Rio",
      fuelTankCapacity: "45 L",
      rent: 13,
      actualRent: 15,
      changeRentPrice: 2,
      seatingCapacity: 5,
      transmission: "Manual / Automatic",
      img: "/images/hatchback/rio.jpg",
      alt: "Image of a Kia Rio hatchback",
      favourite: false,
      rating: 3.3,
      reviewersCount: 410,
      description:
        "A compact and efficient hatchback perfect for city driving and daily use.",
    },
    {
      id: 73,
      name: "Suzuki Swift",
      fuelTankCapacity: "37 L",
      rent: 12,
      actualRent: 14,
      changeRentPrice: 2,
      seatingCapacity: 5,
      transmission: "Manual / Automatic",
      img: "/images/hatchback/swift.jpg",
      alt: "Image of a Suzuki Swift hatchback",
      favourite: true,
      rating: 3.7,
      reviewersCount: 500,
      description:
        "A compact and efficient hatchback perfect for city driving and daily use.",
    },
    {
      id: 74,
      name: "Mazda 3 Hatchback",
      fuelTankCapacity: "51 L",
      rent: 20,
      actualRent: 22,
      changeRentPrice: 2,
      seatingCapacity: 5,
      transmission: "Automatic",
      img: "/images/hatchback/mazda3.jpg",
      alt: "Image of a Mazda 3 hatchback",
      favourite: true,
      rating: 4.2,
      reviewersCount: 340,
      description:
        "A compact and efficient hatchback perfect for city driving and daily use.",
    },
    {
      id: 75,
      name: "Peugeot 208",
      fuelTankCapacity: "44 L",
      rent: 14,
      actualRent: 16,
      changeRentPrice: 2,
      seatingCapacity: 5,
      transmission: "Automatic",
      img: "/images/hatchback/208.jpg",
      alt: "Image of a Peugeot 208 hatchback",
      favourite: false,
      rating: 3.5,
      reviewersCount: 300,
      description:
        "A compact and efficient hatchback perfect for city driving and daily use.",
    },
    {
      id: 76,
      name: "Mini Cooper",
      fuelTankCapacity: "40 L",
      rent: 25,
      actualRent: 28,
      changeRentPrice: 3,
      seatingCapacity: 4,
      transmission: "Automatic",
      img: "/images/hatchback/mini.jpg",
      alt: "Image of a Mini Cooper hatchback",
      favourite: true,
      rating: 4.4,
      reviewersCount: 220,
      description:
        "A compact and efficient hatchback perfect for city driving and daily use.",
    },
  ],
};

export const footerLinks = [
  {
    header: "About",
    sublinks: [
      { title: "How it works", link: "", id: 0 },
      { title: "Featured", link: "https://www.discord.com", id: 1 },
      { title: "Partnership", link: "https://www.discord.com", id: 2 },
      { title: "Bussiness Relation", link: "https://www.discord.com", id: 3 },
    ],
  },
  {
    header: "Community",
    sublinks: [
      { title: "Events", link: "https://www.discord.com", id: 0 },
      { title: "Blog", link: "https://www.discord.com", id: 1 },
      { title: "Podcast", link: "https://www.discord.com", id: 2 },
      { title: "Invite a friend", link: "https://www.discord.com", id: 3 },
    ],
  },
  {
    header: "Socials",
    sublinks: [
      { title: "Discord", link: "https://www.discord.com", id: 0 },
      { title: "Instagram", link: "https://www.instagram.com", id: 1 },
      { title: "Twitter", link: "https://www.twitter.com", id: 2 },
      { title: "Facebook", link: "https://www.facebook.com", id: 3 },
    ],
  },
];
export const cities = [
  { id: 1, name: "Karachi" },
  { id: 2, name: "Lahore" },
  { id: 3, name: "Islamabad" },
  { id: 4, name: "Rawalpindi" },
  { id: 5, name: "Faisalabad" },
  { id: 6, name: "Multan" },
  { id: 7, name: "Peshawar" },
  { id: 8, name: "Quetta" },
  { id: 9, name: "Sialkot" },
  { id: 10, name: "Hyderabad" },
];
